const styles = {
  popupContainer: {
    width: "300px",
    backgroundColor: "#1a1a1a",
    padding: "15px",
    borderRadius: "8px",
    textAlign: "left",
    color: "#ffffff",
    position: "relative",
  },
  popupTitle: {
    fontSize: "16px",
    fontWeight: "bold",
    marginBottom: "8px",
    color: "#ffcc00",
  },
  popupSummary: {
    fontSize: "14px",
    lineHeight: "1.5",
    color: "#cccccc",
    marginBottom: "10px",
  },
  readMoreButton: {
    width: "100%",
    padding: "8px",
    backgroundColor: "#ff4d4f",
    color: "#fff",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "bold",
  },
  closeButton: {
    position: "absolute",
    top: 5,
    right: 10,
    background: "transparent",
    border: "none",
    color: "#fff",
    fontSize: "16px",
    cursor: "pointer",
  },
  voteRow: {
    display: "flex",
    justifyContent: "space-between",
    marginTop: "12px",
    gap: "8px",
  },
  voteButton: {
    flex: 1,
    padding: "8px",
    borderRadius: "6px",
    fontWeight: "bold",
    fontSize: "14px",
    cursor: "pointer",
    border: "none",
  },

  // 🔴 Modal Styles for AddNewsModal
  modalBackdrop: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100vw",
    height: "100vh",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    backdropFilter: "blur(3px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 9999,
  },
  modalContent: {
    width: "360px",
    backgroundColor: "#2c2c2c",
    borderRadius: "10px",
    padding: "20px",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.4)",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    color: "#fff",
  },
  input: {
    padding: "8px 12px",
    fontSize: "14px",
    borderRadius: "6px",
    border: "1px solid #888",
    backgroundColor: "#1e1e1e",
    color: "#f5f5f5",
    outline: "none",
  },
  clearButton: {
    padding: "8px 16px",
    backgroundColor: "#666",
    color: "#fff",
    fontSize: "13px",
    fontWeight: "bold",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
  },
};

export default styles;
